### PR TITLE
Fix linked node modules

### LINKED ISSUE #10013: npm install fails when node_modules is a symlink
Steps to reproduce:

```
cd `mktemp -d`
npm init --force
ln -s `mktemp -d` node_modules
npm install --save-dev typescript@1.7.0-dev.20151006
npm install --save-dev typescript@1.7.0-dev.20151014
```

Gives the following warning:

```
npm WARN update-linked node_modules/typescript needs updating to 1.7.0-dev.20151014 from 1.7.0-dev.20151006 but we can't, as it's a symlink
```

which should be an error because the install has **not** updated the installed version:

```
$ ./node_modules/.bin/tsc --version
message TS6029: Version 1.7.0-dev.20151006
```

Repeat the above but without a symlinked `node_modules` and it works just fine:

```
$ ./node_modules/.bin/tsc --version
message TS6029: Version 1.7.0-dev.20151014
```

Important details:

```
$ node --version
v4.2.0
$ npm --version
3.3.8
```

### PR DESCRIPTION
**Pull request by iarna**
This will fix https://github.com/npm/npm/issues/10013

### CODE REVIEW

File: rpt.js [hunk 1]
```diff
@@ -6,6 +6,23 @@ var once = require('once')
...
+  items.forEach(function (item) {
+    todo(item, handleComplete)
+  })
+  function handleComplete (err) {
+    if (seenErr) return
+    if (err) {
+      seenErr = true
+      return done(err)
+    }
+    if (--remaining === 0) done()
```
Comment (othiym23) [inline rpt.js:22]: my recently-inflamed paranoia around race conditions prompts me to ask if this would be better replaced with `--remaining < 1`

**Comment by othiym23** [comment]
One nit above, but otherwise :sheep::rocket::fire:.

File: rpt.js (hunk 1 above)
Comment (iarna) [inline rpt.js:22]: sounds good to me
